repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.4  # Replace with latest Ruff version
    hooks:
      - id: ruff
        args: ["format"]
      - id: ruff
        args: ["check", "--fix"]
