apiVersion: v1
kind: Secret
metadata:
  name: django-secret
type: Opaque
data:
  django_secret_token: {{ .Values.secretData.django_secret | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  password: {{ .Values.secretData.db_password | b64enc }}
