apiVersion: v1
kind: Secret
metadata:
  name: django-secret
type: Opaque
data:
  django_secret_token: {{ .Values.secretData.django_secret | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  password: {{ .Values.secretData.db_password | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: google-credentials
type: Opaque
data:
  client_id: {{ .Values.secretData.google_client_id | b64enc }}
  secret_key: {{ .Values.secretData.google_secret_key | b64enc }}
