image:
  repository: 977098986372.dkr.ecr.us-west-2.amazonaws.com/dda_backend
  pullPolicy: IfNotPresent
  tag: "v0.1.0"

imagePullSecrets:
  - name: ecr-creds
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: "helm-auto-service-account"

service:
  type: NodePort
  port: 9000
  nodePort: 32100

ingress:
  enabled: false

resources: {}

livenessProbe:
  httpGet:
    path: /v1/glb/health/full
    port: http
readinessProbe:
  httpGet:
    path: /v1/glb/health/full
    port: http

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

volumes: []

volumeMounts: []

nodeSelector: {}

tolerations: []

affinity: {}
