# Generated by Django 5.1.6 on 2025-03-08 07:43

import dda.v1.models.user
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('deleted_at', models.DateField(default=None)),
                ('email', models.CharField()),
                ('family_name', models.CharField()),
                ('given_name', models.CharField()),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('is_email_verified', models.BooleanField(default=False)),
                ('phone_number', models.CharField()),
                ('profile_picture', models.CharField()),
                ('source', models.CharField(choices=[('GOOGLE', 'google')])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SessionToken',
            fields=[
                ('token', models.CharField(primary_key=True, serialize=False)),
                ('expires_at', models.DateField(default=dda.v1.models.user._get_expiry_date)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='v1.user')),
            ],
        ),
    ]
