# Generated by Django 5.1.6 on 2025-03-08 09:15

import dda.v1.models.user
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0001_create_user_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessiontoken',
            name='token',
            field=models.CharField(default=dda.v1.models.user._generate_session_token, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sessiontoken',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='session', to='v1.user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(unique=True),
        ),
    ]
