# Generated by Django 5.1.6 on 2025-07-05 06:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("v1", "0002_sessiontoken_expires_at_as_datetime"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_phone_verified",
            field=models.BooleanField(default=False),
        ),
    ]
