# Generated by Django 5.1.6 on 2025-07-06 00:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("v1", "0003_user_is_phone_verified"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppRole",
            fields=[
                ("created_at", models.DateField(auto_now_add=True)),
                ("updated_at", models.DateField(auto_now=True)),
                ("deleted_at", models.DateField(default=None, null=True)),
                ("role_name", models.CharField(primary_key=True, serialize=False)),
                ("friendly_role_name", models.CharField(unique=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Campaign",
            fields=[
                ("created_at", models.DateField(auto_now_add=True)),
                ("updated_at", models.DateField(auto_now=True)),
                ("deleted_at", models.DateField(default=None, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField()),
                ("description", models.CharField()),
                ("icon", models.CharField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PLANNING", "PLANNING"),
                            ("IN_PROGRESS", "IN PROGRESS"),
                            ("COMPLETED", "COMPLETED"),
                            ("ABANDONED", "ABANDONED"),
                        ]
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="v1.user",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AppResourceRole",
            fields=[
                ("created_at", models.DateField(auto_now_add=True)),
                ("updated_at", models.DateField(auto_now=True)),
                ("deleted_at", models.DateField(default=None, null=True)),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="v1.user"
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="v1.approle"
                    ),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="v1.campaign"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
