# Generated by Django 5.1.6 on 2025-07-06 00:22

from django.db import migrations


def create_roles(apps, schema_editor):
    AppRole = apps.get_model("v1", "AppRole")
    AppRole.objects.create(role_name="dda.v1.gm", friendly_role_name="Game Master")
    AppRole.objects.create(role_name="dda.v1.plyr", friendly_role_name="Player")
    AppRole.objects.create(role_name="dda.v1.admin", friendly_role_name="Administrator")


class Migration(migrations.Migration):
    dependencies = [
        ("v1", "0004_approle_campaign_appresourcerole"),
    ]

    operations = [migrations.RunPython(create_roles)]
