image:
  repository: 977098986372.dkr.ecr.us-west-2.amazonaws.com/dda_backend
  pullPolicy: IfNotPresent
  tag: "v0.1.1"

# Need to figure out how this works in a production
# environment...
imagePullSecrets:
  - name: ecr-creds
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: "helm-auto-service-account"

service:
  type: LoadBalancer
  port: 9000

ingress:
  enabled: false

livenessProbe:
  httpGet:
    path: /v1/glb/health/full
    port: http
readinessProbe:
  httpGet:
    path: /v1/glb/health/full
    port: http

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

env:
  DJANGO_ENV: LOCAL

migration:
  enabled: true

pooler:
  db_host: "host.minikube.internal"
  db_port: 5432
  db_user: admin
  db_name: dda_db
